# Generated by Django 2.0 on 2018-08-05 22:04

from django.db import migrations, models
import django_tutorial.dicts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_tutorial.dicts.models.InitcapField(max_length=128)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_tutorial.dicts.models.InitcapField(max_length=128)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='interest',
            name='tags',
            field=models.ManyToManyField(to='dicts.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='gender',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('name',)},
        ),
    ]
