# Generated by Django 2.0 on 2018-07-15 21:42
from django.contrib.auth.models import User
from django.db import migrations

from django_tutorial.accounts.models import Profile


def create_missed_profiles(apps, schema_editor):
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_missed_profiles)
    ]
