# Generated by Django 2.0 on 2018-08-07 14:00
from django.contrib.auth.models import User
from django.db import migrations
from rest_framework.authtoken.models import Token


def create_new_tokens(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        token = Token.objects.get_or_create(user=user)
        print(token)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180805_2207'),
    ]

    operations = [
        migrations.RunPython(create_new_tokens)
    ]



